# fly.toml app configuration file generated for my-first-astro-blog on 2023-12-23T09:27:41+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-first-astro-blog"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
